// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Issue struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Login struct {
	Email string `json:"email"`
}

type Mutation struct {
}

type NewIssue struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
